auto

diff --git a/rc/bin/container b/rc/bin/container
--- a/rc/bin/container
+++ b/rc/bin/container
@@ -1,22 +1,62 @@
 #!/usr/bin/env bash
 
 # TODO: --help or man page y --help en bats.bash
+# TODO: add docker password
+# TODO: add fzf ?
+
 . arrays.bash
 . helper.sh
-set -eu
+
 declare -Ag IMAGES=(
   ["3.10"]=python:3.10-alpine
-  ["3.10-bullseye"]=python:3.10-bullseye  # latest
+  ["3.10-bullseye"]=python:3.10-bullseye # latest
   ["3.10-slim"]=python:3.10-slim
   ["debian-backports"]=debian:bullseye-backports
   ["debian-slim"]=debian:bullseye-slim
-  ["kali"]=kalilinux:kali-rolling
-  ["kali-bleeding"]=kalilinux:kali-bleeding-edge
-  ["zsh"]=zshusers:zsh
+  ["kali"]=kalilinux/kali-rolling
+  ["kali-bleeding"]=kalilinux/kali-bleeding-edge
+  ["nixos"]=nixos/nix
+  ["zsh"]=zshusers/zsh
 )
-for i in alpine archlinux bash busybox centos debian fedora nixos ubuntu; do
+for i in alpine archlinux bash busybox centos debian fedora ubuntu; do
   IMAGES["${i}"]="${i}"
 done
+
+#######################################
+# run all jobs
+# Arguments:
+#   @   arguments to container
+# Alternative:
+#  export description dest entrypoint IMAGES t opts volume
+#  export -f run
+#  parallel --keep-order --halt now,fail=1 -j "${#IMAGES[@]}" run "{}" "$@" ::: < <(printf '%s\n' "${IMAGES[@]}") || r=$?
+#######################################
+all() {
+  local desc false i image out pid status=0 true
+  declare -A jobs
+  out="$(mktemp -d)"
+  true="$(show)"
+  false="$(false || show)"
+
+  for i in "${IMAGES[@]}"; do
+    run "${i}" "$@" >"${out}/$!.stdout" 2>/"${out}/$!.stderr" &
+    jobs[${i}]=$!
+    for image in "${!jobs[@]}"; do
+      desc="$(description::color "${image}" "$@")"
+      pid="${jobs[${image}]}"
+
+      if wait "${pid}"; then
+        >&2 echo "${true} ${desc}"
+        ! test -s "${out}/${pid}.stdout" || cat "${out}/${pid}.stdout"
+      else
+        status=1
+        >&2 echo "${false} ${desc}"
+        ! test -s "${out}/${pid}.stderr" || cat "${out}/${pid}.stderr"
+      fi
+    done
+  done
+  exit $status
+}
 
 #######################################
 # check argument or die
@@ -27,6 +67,18 @@ done
 check() { [ "${2-}" ] || die "$1"; }
 
 #######################################
+# run the command
+# Arguments:
+#  image    the image.
+#######################################
+run() {
+  local image="$1"
+  shift
+  $description "${image}" "$@" \
+    && docker run -i "${t[@]}" "${opts[@]}" "${entrypoint[@]}" -v "${volume}:${dest}" "${image}" "$@"
+}
+
+#######################################
 # run command in a container, with no arguments for run will go to console/terminal
 # Globals:
 #   IMAGES
@@ -34,19 +86,37 @@ check() { [ "${2-}" ] || die "$1"; }
 #  None
 #######################################
 main() {
-  local command commands="commands name names image images run" dest entrypoint=( ) image images
-  local msg name names opts=( --rm ) t=() volume
-  images="$(sort -t ' ' <<< "${IMAGES[*]}")"
-  names="$(sort -t ' ' <<< "${!IMAGES[*]}")"
+  local all=false command commands="commands name names image images run" image images
+  local msg name names
+  description=:
+  entrypoint=()
+  t=()
+  opts=(--rm)
+  images="$(sort -t ' ' <<<"${IMAGES[*]}")"
+  names="$(sort -t ' ' <<<"${!IMAGES[*]}")"
 
-  [ "${1-}" != '--sh' ] || { entrypoint=( --entrypoint /bin/sh ); shift; }
+  [ "${1-}" != '--sh' ] || {
+    entrypoint=(--entrypoint /bin/sh)
+    shift
+  }
+
   check "Invalid Command: '${1-}', Valid Commands: [${commands}]" "${1-}" || exit
-  command="$1"; shift
+  command="$1"
+  shift
   name="${1-}"
   msg="Invalid Name/Image: '${name}', Valid Names: [${names}], Valid Images [${images}]"
 
   case "${command}" in
-    commands) tr ' ' '\n' <<< "${commands}" && exit ;;
+    all)
+      if [ "${GITHUB_RUN_ID-}" ] || [ "${TESTS_LOCAL:-1}" -eq 0 ]; then
+        exit
+      fi
+      set +u
+      cmd description::color || { . bats.bash && description=description::color; }
+      set -u
+      all=true
+      ;;
+    commands) tr ' ' '\n' <<<"${commands}" && exit ;;
     name)
       msg="Invalid Image: '${name}', Valid Images: [${images}]"
       check "${msg}" "${name}" || exit
@@ -59,9 +129,10 @@ main() {
     names) printf '%s\n' "${!IMAGES[@]}" | sort && exit ;;
     image)
       msg="Invalid Name: '${name}', Valid Names: [${names}]"
-      check "${msg}"  "${name}" || exit
+      check "${msg}" "${name}" || exit
       getkey "${name}" IMAGES 2>/dev/null || die "${msg}"
-      echo && exit;;
+      echo && exit
+      ;;
     images) printf '%s\n' "${IMAGES[@]}" | sort && exit ;;
     run)
       check "${msg}" "${name}" || exit
@@ -70,16 +141,14 @@ main() {
     *) false || die "Invalid Command: '${command}', Valid Commands: [${commands}]" ;;
   esac
 
-  # TODO: check if image in registry if not in list
-  # TODO: add docker password
-  # TODO: add entry point
-  # TODO: add --all for run. no
-  image="${IMAGES["${name}"]-}"
-  if [ ! "${image-}" ]; then
-    if inarray "${name}" IMAGES 2>/dev/null || docker manifest inspect --insecure "${name}" 2>/dev/null; then
-      image="${name}"
-    else
-       die "${msg}, or Invalid Manifest [docker manifest inspect --insecure ${name}]"
+  if ! $all; then
+    image="${IMAGES["${name}"]-}"
+    if [ ! "${image-}" ]; then
+      if inarray "${name}" IMAGES 2>/dev/null || docker manifest inspect --insecure "${name}" 2>/dev/null; then
+        image="${name}"
+      else
+        die "${msg}, or Invalid Manifest [docker manifest inspect --insecure ${name}]"
+      fi
     fi
   fi
 
@@ -89,20 +158,16 @@ main() {
 
   if [ -f "${volume}/entrypoint.sh" ]; then
     [ ! "${entrypoint-}" ] || die "--sh for --entrypoint /bin/sh can not be used if ${dest}/entrypoint.sh"
-    entrypoint=( --entrypoint "${dest}/entrypoint.sh" )
+    entrypoint=(--entrypoint "${dest}/entrypoint.sh")
   fi
 
-  ! test -t 0 || t=( -t )
-  docker run -i "${t[@]}" "${opts[@]}" "${entrypoint[@]}" -v "${volume}:${dest}" "${image}" "$@"
+  ! test -t 0 || t=(-t)
+
+  if $all; then
+    all "$@"
+  else
+    run "${image}" "$@"
+  fi
 }
 
 main "$@"
-
-## NO entrypoint.sh
-# container run alpine ## Enters sh without prompt (the default entrypoint)
-# container run alpine ls -la
-# container run alpine 'RC_PREFIX=/rc . ./rc/rc/profile; env'
-
-## entrypoint.sh
-# container run alpine ls -la
-# container run alpine -c color
